Forking netcfg to netctl (2/2)
This commit contains the refactoring and rewriting of code.

diff --git a/src/lib/connections/ethernet b/src/lib/connections/ethernet
--- a/src/lib/connections/ethernet
+++ b/src/lib/connections/ethernet
@@ -1,279 +1,75 @@
-#! /bin/bash
-# Source file for the 'ethernet' connection
-#   ethernet_up $profile
-#   ethernet_down $profile
-#   ethernet_status
+# Ethernet connection support for netctl
 
-. /usr/lib/network/network
+. "$SUBR_DIR/ip"
 
-report_iproute()
-{
-    report_fail "$*"
-    bring_interface down "$INTERFACE"
-    exit 1
-}
 
 ethernet_up() {
-    load_profile "$1"
-    SYSCTL_INTERFACE="${INTERFACE/.//}"
-
-    if ! is_interface "$INTERFACE"; then
-        report_iproute "Interface $INTERFACE does not exist"
-    fi
-
-    # Disable IPv6 before bringing the interface up to prevent SLAAC
-    if [[ "$IP6" == "no" ]]; then
-        sysctl -q -w "net.ipv6.conf.$SYSCTL_INTERFACE.disable_ipv6=1"
-    fi
-
-    report_debug ethernet_up bring_interface up "$INTERFACE"
-    bring_interface up "$INTERFACE"
-
-    if ! checkyesno "${SKIPNOCARRIER:-no}"; then
-        # Some cards are plain slow to come up. Don't fail immediately.
-        if ! timeout_wait "${CARRIER_TIMEOUT:-5}" '(( $(< "/sys/class/net/$INTERFACE/carrier") ))'; then
-            report_iproute "No connection"
-        fi
-    fi
-
-
-    if checkyesno "${AUTH8021X:-no}"; then
-        . "$SUBR_DIR/8021x"
-        [[ -z "$WPA_CONF" ]] && WPA_CONF="/etc/wpa_supplicant.conf"
-        [[ -z "$WPA_DRIVER" ]] && WPA_DRIVER="wired"
-
-        report_debug ethernet_up start_wpa "$INTERFACE" "$WPA_CONF" "$WPA_DRIVER" "$WPA_OPTS"
-        if ! start_wpa "$INTERFACE" "$WPA_CONF" "$WPA_DRIVER" "$WPA_OPTS"; then
-            report_fail "wpa_supplicant did not start, possible configuration error"
-            return 1
-        fi
-
-        if ! wpa_check "$INTERFACE" "$TIMEOUT" "ASSOCIATED"; then
-            bring_interface down "$INTERFACE"
-            report_fail "WPA Authentication/Association Failed"
-            return 1
-        fi
-    fi
-
-    if [[ -z "$IP" && -z "$IP6" ]]; then
-        report_iproute "At least one of IP or IP6 should be specified"
+    if ! is_interface "$Interface"; then
+        report_error "Interface '$Interface' does not exist"
         return 1
     fi
 
-    case "$IP" in
-    dhcp)
-        if checkyesno "${DHCLIENT:-no}"; then
-            rm -r "/run/dhclient-${INTERFACE}.pid" >/dev/null 2>&1
-            report_debug ethernet_up dhclient -q -e TIMEOUT="${DHCP_TIMEOUT:-10}" -pf "/run/dhclient-$INTERFACE.pid" "$INTERFACE"
-            if ! dhclient -q -e TIMEOUT="${DHCP_TIMEOUT:-10}" -pf "/run/dhclient-${INTERFACE}.pid" ${DHCLIENT_OPTIONS} "$INTERFACE"; then
-                report_fail "DHCP IP lease attempt failed."
-                stop_80211x
-                return 1
-            fi
-        else
-            # Clear remaining pid files.
-            rm -f "/run/dhcpcd-$INTERFACE".{pid,cache} >/dev/null 2>&1
-            # If using own dns, tell dhcpcd to NOT replace resolv.conf
-            [[ -n "$DNS" ]] && DHCP_OPTIONS="-C resolv.conf $DHCP_OPTIONS"
-            # Start dhcpcd
-            report_debug ethernet_up dhcpcd -qL -t "${DHCP_TIMEOUT:-10}" $DHCPCD_INTERNAL_OPTIONS $DHCP_OPTIONS "$INTERFACE"
-            dhcpcd -qL -t "${DHCP_TIMEOUT:-10}" $DHCPCD_INTERNAL_OPTIONS $DHCP_OPTIONS "$INTERFACE" 2>&1 | report_debug "$(cat)"
-            if [[ "$PIPESTATUS" -ne 0 ]]; then
-                report_fail "DHCP IP lease attempt failed."
-                stop_80211x
-                return 1
-            fi
-        fi
-        ;;
-    static)
-        if [[ -n "$ADDR" ]]; then
-            [[ -z $NETMASK ]] && NETMASK=24
-            report_debug ethernet_up ip addr add "$ADDR/$NETMASK" brd + dev "$INTERFACE"
-            if ! ip addr add "$ADDR/$NETMASK" brd + dev "$INTERFACE"; then
-                report_iproute "Could not configure interface"
-            fi
-        fi
-        if [[ -n "$GATEWAY" ]]; then
-            report_debug ethernet_up ip route add default via "$GATEWAY" dev "$INTERFACE"
-            if ! ip route add default via "$GATEWAY" dev "$INTERFACE"; then
-                report_iproute "Adding gateway $GATEWAY failed"
-            fi
-        fi
-        ;;
-    ""|no)
-        ;;
-    *)
-        report_iproute "IP must be either 'dhcp', 'static' or 'no'"
-        ;;
-    esac
-
-    if [[ -n "$IP" && -n "$ROUTES" ]]; then
-        for route in "${ROUTES[@]}"; do
-            report_debug ethernet_up ip route add $route dev "$INTERFACE"
-            if ! ip route add $route dev "$INTERFACE"; then
-                report_iproute "Adding route '$route' failed"
-            fi
-        done
+    # Disable IPv6 before bringing the interface up to prevent SLAAC
+    if [[ $IP6 == "no" ]]; then
+        sysctl -q -w "net.ipv6.conf.${Interface/.//}.disable_ipv6=1"
     fi
 
-    # Load ipv6 module if necessary (FS#25530)
-    case "$IP6" in
-    dhcp*|stateless|static)
-        [[ -d "/proc/sys/net/ipv6" ]] || modprobe ipv6
-        ;;
-    no)
-        [[ -d "/proc/sys/net/ipv6" ]] && sysctl -q -w "net.ipv6.conf.$SYSCTL_INTERFACE.accept_ra=0"
-        ;;
-    "")  # undefined IP6 does not prevent RA's from being received -> nop
-        ;;
-    *)
-        report_iproute "IP6 must be 'dhcp', 'dhcp-noaddr', 'stateless', 'static' or 'no'"
-        ;;
-    esac
+    if ! bring_interface_up "$Interface"; then
+        report_error "Failed to bring interface '$Interface' up"
+        return 1
+    fi
 
-    case "$IP6" in
-    dhcp*)
-        if ! type dhclient &>/dev/null; then
-            report_fail "You need to install dhclient to use DHCPv6."
-            stop_80211x
+    if ! is_yes "${SkipNoCarrier:-no}"; then
+        # Some cards are plain slow to come up. Don't fail immediately.
+        if ! timeout_wait "${TimeoutCarrier:-5}" '(( $(< "/sys/class/net/$Interface/carrier") ))'; then
+            report_error "No connection on interface '$Interface'"
+            bring_interface_down "$Interface"
             return 1
         fi
-        sysctl -q -w "net.ipv6.conf.$SYSCTL_INTERFACE.accept_ra=1"
-        if [[ "$IP6" == "dhcp-noaddr" ]]; then
-            DHCLIENT6_OPTIONS="-S ${DHCLIENT6_OPTIONS}"
-        fi
-        _DHCLIENT_PIDFILE="/run/dhclient6-${INTERFACE}.pid"
-        rm -r ${_DHCLIENT_PIDFILE} &>/dev/null
-        report_debug ethernet_up dhclient -6 -q -e TIMEOUT="${DHCP_TIMEOUT:-10}" -pf ${_DHCLIENT_PIDFILE} "$INTERFACE"
-        if ! dhclient -6 -q -e TIMEOUT="${DHCP_TIMEOUT:-10}" -pf ${_DHCLIENT_PIDFILE} ${DHCLIENT6_OPTIONS} "$INTERFACE"; then
-            report_fail "DHCPv6 IP lease attempt failed."
-            stop_80211x
+    fi
+
+
+    if is_yes "${Auth8021X:-no}"; then
+        . "$SUBR_DIR/8021x"
+        : ${WPAConfigFile:=/etc/wpa_supplicant.conf}
+        : ${WPADriver:=wired}
+        : ${TimeoutWPA:=15}
+
+        if ! wpa_start "$Interface" "$WPADriver" "$WPAConfigFile"; then
+            report_error "The WPA supplicant did not start for interface '$Interface'"
+            bring_interface_down "$Interface"
             return 1
         fi
-        ;;
-    stateless)
-        sysctl -q -w "net.ipv6.conf.$SYSCTL_INTERFACE.accept_ra=1"
-        ;;
-    static)
-        sysctl -q -w "net.ipv6.conf.$SYSCTL_INTERFACE.accept_ra=0"
-        if [[ -n "$ADDR6" ]]; then
-            for addr in "${ADDR6[@]}"; do
-                report_debug ethernet_up ip -6 addr add $addr dev "$INTERFACE"
-                if ! ip -6 addr add $addr dev "$INTERFACE"; then
-                    report_iproute "Could not add address '$addr' to interface"
-                fi
-            done
-        fi
-        ;;
-    esac
 
-    if [[ -n "$IP6" ]]; then
-        # Wait for DAD to finish (FS#28887)
-        report_debug ethernet_up ip -6 addr show dev "$INTERFACE" tentative
-        if ! timeout_wait "${DAD_TIMEOUT:-3}" '[[ -z "$(ip -6 addr show dev "$INTERFACE" tentative)" ]]'; then
-            report_iproute "Duplicate Address Detection is taking too long"
-        fi
-
-        # Add static IPv6 routes
-        if [[ -n "$ROUTES6" ]]; then
-            for route in "${ROUTES6[@]}"; do
-            report_debug ethernet_up ip -6 route add $route dev "$INTERFACE"
-                if ! ip -6 route add $route dev "$INTERFACE"; then
-                    report_iproute "Adding route '$route' failed"
-                fi
-            done
-        fi
-
-        # Set a custom gateway after waiting for DAD to finish
-        if [[ "$IP6" == "static" && -n "$GATEWAY6" ]]; then
-            report_debug ethernet_up ip -6 route replace default via "$GATEWAY6" dev "$INTERFACE"
-            if ! ip -6 route replace default via "$GATEWAY6" dev "$INTERFACE"; then
-                report_iproute "Adding gateway $GATEWAY6 failed"
-            fi
+        if ! wpa_wait_until_state "$TimeoutWPA" "$Interface" "ASSOCIATED"; then
+            wpa_stop "$Interface"
+            bring_interface_down "$Interface"
+            report_error "WPA Authentication/Association Failed"
+            return 1
         fi
     fi
 
-    if [[ -n "$IPCFG" ]]; then
-        for line in "${IPCFG[@]}"; do
-            report_debug ethernet_up ip "$line"
-            if ! ip $line; then
-                report_iproute "Could not configure interface ($line)."
-            fi
-        done
+    if ! ip_set; then
+        stop_80211x
+        bring_interface_down "$Interface"
+        return 1
     fi
-
-    # Set hostname
-    if [[ -n "$HOSTNAME" ]]; then
-        report_debug ethernet_up hostname "$HOSTNAME"
-        if ! echo "$HOSTNAME" >/proc/sys/kernel/hostname; then
-            report_iproute "Cannot set hostname to $HOSTNAME"
-        fi
-    fi
-
-    # Generate a new resolv.conf
-    if [[ -n "$DNS" ]]; then
-        : >/etc/resolv.conf
-        [[ -n "$DOMAIN" ]] && echo "domain $DOMAIN" >>/etc/resolv.conf
-        [[ -n "$SEARCH" ]] && echo "search $SEARCH" >>/etc/resolv.conf
-        for dns in "${DNS[@]}"; do
-            echo "nameserver $dns" >>/etc/resolv.conf
-        done
-        for dnsoption in "${DNS_OPTIONS[@]}"; do
-            echo "options $dnsoption" >>/etc/resolv.conf
-        done
-    fi
-
-    return 0
 }
 
 ethernet_down() {
-    load_profile "$1"
-
-    if [[ "$IP" == "dhcp" ]]; then
-        if checkyesno "${DHCLIENT:-no}"; then
-            if [[ -f "/run/dhclient-$INTERFACE.pid" ]]; then
-                report_debug ethernet_down dhclient -q -x "$INTERFACE" -pf "/run/dhclient-$INTERFACE.pid"
-                dhclient -q -x "$INTERFACE" -pf "/run/dhclient-$INTERFACE.pid" &>/dev/null
-                #dhclient -q -r "$INTERFACE" &>/dev/null
-            fi
-        else
-            if [[ -f "/run/dhcpcd-$INTERFACE.pid" ]]; then
-                report_debug ethernet_down dhcpcd -qk "$INTERFACE"
-                dhcpcd -qk "$INTERFACE" &>/dev/null
-            fi
-        fi
-    fi
-    if [[ "$IP6" == dhcp* ]]; then
-        if [[ -f "/run/dhclient6-$INTERFACE.pid" ]]; then
-            report_debug ethernet_down dhclient -6 -q -x "$INTERFACE" -pf "/run/dhclient6-$INTERFACE.pid"
-            dhclient -6 -q -x "$INTERFACE" -pf "/run/dhclient6-$INTERFACE.pid" &>/dev/null
-            report_debug ethernet_down /bin/kill $(< /run/dhclient6-$INTERFACE.pid)
-            /bin/kill $(< /run/dhclient6-$INTERFACE.pid) &>/dev/null
-        fi
-    fi
-
+    ip_unset
     stop_80211x
-
-    if [[ "$CONNECTION" == "wireless" ]]; then
-        report_debug ethernet_down bring_interface flush "$INTERFACE"
-        bring_interface flush "$INTERFACE"
-    else
-        report_debug ethernet_down bring_interface down "$INTERFACE"
-        bring_interface down "$INTERFACE"
-    fi
-    return 0
+    bring_interface_down "$Interface"
 }
 
 # Stop wpa_supplicant if neccessary
 stop_80211x() {
-    if checkyesno "${AUTH8021X:-no}"; then
+    if is_yes "${Auth8021X:-no}"; then
         . "$SUBR_DIR/8021x"
-        [[ -z "$WPA_CONF" ]] && WPA_CONF="/etc/wpa_supplicant.conf"
-        report_debug ethernet_down stop_wpa "$INTERFACE"
-        stop_wpa "$INTERFACE"
+        : ${WPAConfigFile:=/etc/wpa_supplicant.conf}
+        do_debug wpa_stop "$Interface"
     fi
 }
 
-ethernet_$1 "$2"
-exit $?
+
 # vim: set ts=4 et sw=4:
diff --git a/src/lib/network b/src/lib/network
--- a/src/lib/network
+++ b/src/lib/network
@@ -1,368 +1,95 @@
-### Globals
+#! /bin/bash
+
 . /usr/lib/network/globals
-# will load hooks
 
-## Loads a profile.
-# $1: profile name
-load_profile()
-{
-    unset ROUTES
-    [[ -z "$1" ]] && return 1
-    if [[ ! -f "$PROFILE_DIR/$1" ]]; then
-        report_err "Profile \"$1\" does not exist"
-        return 1
-    fi
-    report_debug "Loading profile $1"
-    INTERFACE=$(. "$PROFILE_DIR/$1"; echo "$INTERFACE")
-    report_debug "Configuring interface $INTERFACE"
-    if [[ -z "$INTERFACE" ]]; then
-        report_err "Profile missing an interface to configure"
-        return 1
-    fi
-    if [[ -f "$IFACE_DIR/$INTERFACE" ]]; then
-        report_debug "Interface level configuration enabled: $IFACE_DIR/$INTERFACE"
-        . "$IFACE_DIR/$INTERFACE"
-    fi
-    . "$PROFILE_DIR/$1" # we want profile settings to override, so need to source profile again
-    if [[ ! -f "$CONN_DIR/$CONNECTION" ]]; then
-        report_err "$CONNECTION is not a valid connection, check spelling or look at examples"
-        return 1
-    fi
-}
 
-##################
-# Profile up/down
-##################
-
-## Take all registered profiles down.
-all_down()
-{
-    find "$STATE_DIR/profiles/" -maxdepth 1 -type f -printf '%f\n' \
-    | while read prof; do
-        profile_down "$prof"
-    done
-}
-
-## Create the state dir and sub directories if they don't already exist.
-check_make_state_dir()
-{
-    [[ ! -d "$STATE_DIR" ]] && mkdir -p "$STATE_DIR"/{interfaces,profiles}
-    for d in interfaces profiles suspend; do
-        [[ ! -d "$STATE_DIR/$d" ]] && mkdir "$STATE_DIR/$d"
-    done
-}
-
-## Save the list of running profiles and take them down if needed
-# $1: interface name or "all"
-# $2: take associated profiles down (optional, default="yes")
-interface_suspend()
-{
-    report_debug interface_suspend "$@"
-
-    check_make_state_dir
-    find "$STATE_DIR/profiles/" -maxdepth 1 -type f -printf '%f\n' \
-    | while read prof; do
-        # the pipe to "while read" will create a subshell
-        INTERFACE=$(. "$STATE_DIR/profiles/$prof"; echo "$INTERFACE")
-        if [[ "$1" == all || "$1" == "$INTERFACE" ]]; then
-            report_notice "suspending interface $INTERFACE with profile $prof"
-            cp "$STATE_DIR/profiles/$prof" "$STATE_DIR/suspend/"
-            if checkyesno "${2:-yes}"; then
-                profile_down "$prof"
-            fi
-        fi
-    done
-}
-
-## Save the list of all running profiles and take them down
-all_suspend() {
-    interface_suspend all
-}
-
-## Restore saved profiles (for resume purposes).
-# $@: a list of interfaces not to resume (e.g., because they're disabled)
-all_resume()
-{
-    report_debug all_resume "$@"
-    find "$STATE_DIR/suspend/" -maxdepth 1 -type f -printf '%f\n' \
-    | while read prof; do
-        # the pipe to "while read" will create a subshell
-        INTERFACE=$(. "$STATE_DIR/suspend/$prof"; echo "$INTERFACE")
-        if [[ $# -eq 0 || ! " $* " =~ " $INTERFACE " ]]; then
-            report_notice "resuming interface $INTERFACE with profile $prof"
-            profile_up "$prof"
-            rm -f "$STATE_DIR/suspend/$prof"   # if profile_up succeeds, it will have already removed this
-        fi
-    done
-}
-
-## Puts up a profile.
-# $1: the profile name
-profile_up()
-{
-    (
-    # Keep inside subshell so that options from one profile don't cross to others
-    # exit 1 used in a subshell is effectively exiting a new process
-    check_make_state_dir
-
-    local status PROFILE="$1"   # save PROFILE in a variable so that it's available to PRE_UP/POST_DOWN etc hooks
-
-    load_profile "$PROFILE" || exit 1
-
-    if check_profile "$PROFILE"; then
-        report_err "$PROFILE already connected"
-        exit 1
-    fi
-
-    # EXCLUSIVE, network.d/profile: Individual profile is mutually exclusive
-    if checkyesno "$EXCLUSIVE"; then
-        all_down
-    fi
-
-    report_try "$PROFILE up"
-
-    status=$(check_iface "$INTERFACE")
-    report_debug "status reported to profile_up as: $status"
-    case "$status" in
-        external)
-            report_fail "Interface $INTERFACE externally controlled"
-            exit 1
-            ;;
-        disabled)
-            report_fail "Interface $INTERFACE is disabled"
-            exit 1
-            ;;
-        "")
-            ;;
-        *)
-            if checkyesno "$CHECK"; then
-                report_fail "Interface $INTERFACE already in use"
-                exit 1
-
-            # not necessary to sandbox this call or reload PROFILE afterwards
-            elif ! interface_down "$INTERFACE"; then
-                report_fail
-                exit 1
-            fi
-            ;;
-    esac
-
-    if ! ( eval $PRE_UP ); then     # JP: sandbox the eval so variables don't bleed into current function
-        report_debug profile_up "PRE_UP failed"
-        report_fail
-        exit 1
-    fi
-
-    if ! "$CONN_DIR/$CONNECTION" up "$PROFILE"; then
-        report_debug profile_up "connect failed"
-        report_fail
-        #  "$CONN_DIR/$CONNECTION" down "$PROFILE" # JP: should we do this to make sure?
-        exit 1
-    fi
-
-    if ! ( eval $POST_UP ); then    # JP: sandbox the eval
-        report_debug profile_up "POST_UP failed"
-        report_fail
-        # failing POST_UP will take interface down
-        "$CONN_DIR/$CONNECTION" down "$PROFILE"
-        exit 1
-    fi
-
-    set_profile up "$PROFILE"
-    unset EXCLUSIVE
-
-    # Successfully running a new profile; erase any suspended profiles on this interface
-    local iface="$INTERFACE"
-    find "$STATE_DIR/suspend/" -maxdepth 1 -type f -printf '%f\n' \
-    | while read prof; do
-        # the pipe to "while read" will create a subshell
-        INTERFACE=$(. "$STATE_DIR/suspend/$prof"; echo "$INTERFACE")
-        if [[ "$iface" == "$INTERFACE" ]]; then
-            rm "$STATE_DIR/suspend/$prof"
-        fi
-    done
-
-    report_success
-    ); return $?
-}
-
-## Puts a profile down.
-# $1: the profile name
-profile_down()
-{
-    (
-    check_make_state_dir
-
-    local status PROFILE="$1"   # save PROFILE in a variable so that it's available to PRE_UP/POST_DOWN etc hooks
-
-    load_profile "$PROFILE" || exit 1
-
-    status=$(check_iface "$INTERFACE")
-    report_debug "status reported to profile_down as: $status"
-
-    if [[ "$status" != "$PROFILE" ]]; then
-        # if interface not available to be controlled by netcfg, then
-        # any profiles should have been removed by check_iface
-        # else we get here if another profile is running
-        report_err "Profile not connected"
-        exit 1
-    fi
-
-    report_try "$PROFILE down"
-    if [[ "$(check_iface "$INTERFACE")" == "external" ]]; then
-        report_fail "$interface was connected by another application"
-        exit 1
-    fi
-
-    if ! ( eval $PRE_DOWN ); then   # JP: sandbox the eval
-        report_debug profile_down "PRE_DOWN failed"
-        # true  # JP: did we want failing PRE_DOWN to leave the profile active?
-        report_fail
-        exit 1
-    fi
-
-    if ! "$CONN_DIR/$CONNECTION" down "$PROFILE"; then
-        report_debug profile_up "disconnect failed"
-        report_fail
-        exit 1
-    fi
-
-    if ! ( eval $POST_DOWN ); then  # JP: sandbox the eval
-        report_debug profile_down "POST_DOWN failed"
-        report_fail
-        exit 1
-    fi
-
-    set_profile down "$PROFILE"
-    report_success
-    ); return $?
-}
-
-# interface_down interface
-#   take interface down
-#
-interface_down()
-{
-    local profile=$(check_iface "$1")
-    case "$profile" in
-        ""|disabled) return 0 ;;
-        external) return 1 ;;
-        *) profile_down "$profile" ;;
-    esac
-}
-
-# interface_reconnect interface
-#   reconnects the profile active on interface
-interface_reconnect()
-{
-    local profile=$(check_iface "$1")
-    case "$profile" in
-        ""|disabled|external)
-            return 1
-        ;;
-        *)
-            profile_down "$profile"
-            profile_up "$profile"
-        ;;
-    esac
-}
-
-##
-# check_iface interface
-#   Return 0 if interface unavailable (in use by a profile or externally, or disabled)
-#   Return 1 if interface down and available to be used
-#
-check_iface() {
-    if [[ -f "$STATE_DIR/interfaces/$1" ]]; then
-        cat "$STATE_DIR/interfaces/$1"
-        return 0
-    else
-        return 1
-    fi
-}
-
-# list_profiles
-#  Outputs a list of all profiles
-list_profiles() {
-    # JP: follow aliases with -L, also skip profiles that start with '.' or end with '~' or '.conf' (so profile.conf can be the wpa.conf file for profile)
-    find -L "$PROFILE_DIR/" -maxdepth 1 -type f -not -name '*~' -not -name '*.conf' -not -name '.*' -printf "%f\n"
-}
-
-# check_profile profile
-#   Return 0 if profile registered as being up
-#   Return 1 if profile not registered
-#
-check_profile() {
-    [[ -f "$STATE_DIR/profiles/$1" && ! -f "$STATE_DIR/suspend/$1" ]] && return 0
-    return 1
-}
-
-### Status setting functions
-##
-# set_profile up/down profile
-#   Set profile state, either up or down
-#
-set_profile() {
-    local INTERFACE
-    if [[ "$1" == "up" ]]; then
-        INTERFACE=$(. "$PROFILE_DIR/$2"; echo "$INTERFACE")
-        cp "$PROFILE_DIR/$2" "$STATE_DIR/profiles/"
-        set_iface up "$INTERFACE" "$2"
-    elif [[ "$1" == "down" && -f "$STATE_DIR/profiles/$2" ]]; then    # JP: skip if profile not already up
-        INTERFACE=$(. "$STATE_DIR/profiles/$2"; echo "$INTERFACE")
-        rm "$STATE_DIR/profiles/$2"
-        set_iface down "$INTERFACE" "$2"
-    fi
-}
-
-# set_iface up/down interface [profile]
-#   Set interface status to up/down
-#   optionally link it to a profile.
-#
-set_iface() {
-    local PROFILE="${3:-external}"
-    if [[ "$1" == "up" ]]; then
-        echo "$PROFILE" > "$STATE_DIR/interfaces/$2"
-    elif [[ "$1" == "down" ]]; then
-        rm -f "$STATE_DIR/interfaces/$2"    # JP: add -f so we don't complain if the interface isn't up
-    fi
-}
-
+## Check if a string represents a network interface
+# $1: potential interface name
 is_interface() {
-    local INTERFACE="$1"
-    if [[ ! -e "/sys/class/net/$INTERFACE" ]]; then
-        if ! echo "$INTERFACE" | grep -F -q ":"; then
-            return 1
-        fi
-    fi
-    return 0
+    # Strip any old school alias specifier
+    [[ -d "/sys/class/net/${1%%:?*}" ]]
 }
 
+## Check if an interface is up
+# $1: interface name
 interface_is_up() {
     local flags
-    read flags < "/sys/class/net/$1/flags"
+    read flags < "/sys/class/net/${1%%:?*}/flags"
     # IFF_UP is defined as 0x1 in linux/if.h
     (( flags & 0x1 ))
 }
 
-## Changes a network interface state.
-# $1: up, flush, or down.
-# $2: the interface name
-bring_interface()
-{
-    local INTERFACE="$2"
-    case "$1" in
-        up)
-            ip link set dev "$INTERFACE" up &>/dev/null
-            timeout_wait "${UP_TIMEOUT:-5}" 'interface_is_up "$INTERFACE"' || return 1
-        ;;
-        flush|down)
-            ip addr flush dev "$INTERFACE" &>/dev/null
-        ;;&
-        down)
-            ip link set dev "$INTERFACE" down &>/dev/null
-        ;;
-    esac
+## Activate an interface
+# $1: interface name
+bring_interface_up() {
+  local interface=$1
+  ip link set dev "$interface" up &>/dev/null
+  timeout_wait "${TimeoutUp:-5}" 'interface_is_up "$interface"'
 }
+
+## Deactivate an interface
+# $1: interface name
+bring_interface_down() {
+  local interface=$1
+  ip addr flush dev "$interface" &>/dev/null
+  ip link set dev "$interface" down &>/dev/null
+  # We reuse the up timeout (down normally is faster)
+  timeout_wait "${TimeoutUp:-5}" '! interface_is_up "$interface"'
+}
+
+
+if [[ $# -ne 2 || $1 != @(start|stop) ]]; then
+    exit_error "Usage: $0 {start|stop} <profile>"
+fi
+ensure_root netctl
+# Ensure we are not in a transient directory
+cd /
+
+# Expose the profile name
+Profile=$2
+load_profile "$Profile"
+source "$CONN_DIR/$Connection"
+case $1 in
+  start)
+    report_notice "Starting network profile '$Profile'..."
+    if is_interface "$Interface" && interface_is_up "$Interface" && \
+       ! is_yes "${ForceConnect:-no}"; then
+        report_error "The interface of network profile '$Profile' is already up"
+        exit 1
+    fi
+    if ! "${Connection}_up"; then
+        report_error "Failed to bring the network up for profile '$Profile'"
+        exit 1
+    fi
+    # JP: sandbox the eval
+    if ! ( eval $ExecUpPost ); then
+        report_error "ExecUpPost failed for network profile '$Profile'"
+        # Failing ExecUpPost will take the connection down
+        "${Connection}_down"
+        exit 1
+    fi
+    report_notice "Started network profile '$Profile'"
+    ;;
+  stop)
+    report_notice "Stopping network profile '$Profile'..."
+    # JP: sandbox the eval
+    if ! ( eval $ExecDownPre ); then
+        report_error "ExecDownPre failed for network profile '$Profile'"
+        # Failing ExecDownPre will leave the profile active
+        exit 1
+    fi
+    if ! "${Connection}_down"; then
+        report_error "Failed to bring the network down for profile '$Profile'"
+        exit 1
+    fi
+    if is_interface "$Interface" && interface_is_up "$Interface" && \
+       ! is_yes "${ForceConnect:-no}"; then
+        report_error "The interface of network profile '$Profile' did not go down"
+        exit 1
+    fi
+    report_notice "Stopped network profile '$Profile'"
+    ;;
+esac
+
 
 # vim: ft=sh ts=4 et sw=4:
diff --git a/src/wifi-menu b/src/wifi-menu
--- a/src/wifi-menu
+++ b/src/wifi-menu
@@ -1,24 +1,21 @@
 #! /bin/bash
 
-. /usr/lib/network/network
+. /usr/lib/network/globals
 . "$SUBR_DIR/8021x"
-. /etc/conf.d/netcfg
+
 
 usage()
 {
     cat << END
-Usage: wifi-menu [-o | --obscure] [-h | --help] [interface]
+Usage: wifi-menu [-h | --help] [-o | --obscure] [interface]
 
 Interactively connect to a wireless network.
 
 Arguments:
+  -h, --help     Show this help.
   -o, --obscure  Show asterisks for the characters of the password
                  and store the password as a hexadecimal string.
-  -h, --help     Show this help.
-  interface      The wireless interface to use.
-                 (default: WIRELESS_INTERFACE from /etc/conf.d/netcfg)
-
-For choosing from all available profiles, use netcfg-menu.
+  interface      The wireless interface to use (default: wlan0).
 END
 }
 
@@ -30,10 +27,10 @@ init_profiles()
     while read profile; do
         essid=$(
             unset INTERFACE ESSID
-            . "$PROFILE_DIR/$profile" &> /dev/null
-            if [[ "$INTERFACE" = "$1" && -n "$ESSID" ]]; then
+            source "$PROFILE_DIR/$profile" > /dev/null
+            if [[ "$Interface" = "$1" && -n "$ESSID" ]]; then
                 printf "%s" "$ESSID"
-                if [[ "$DESCRIPTION" =~ "Automatically generated" ]]; then
+                if [[ "$Description" =~ "Automatically generated" ]]; then
                     return 2
                 else
                     return 1
@@ -61,8 +58,8 @@ init_entries()
     while IFS=$'\t' read signal flags ssid; do
         ENTRIES[i++]="--"  # $ssid might look like an option to dialog.
         ENTRIES[i++]=$ssid
-        if inarray "$ssid" "${ESSIDS[@]}"; then
-            if inarray "$(ssid_to_profile "$ssid")" "${GENERATED[@]}"; then
+        if in_array "$ssid" "${ESSIDS[@]}"; then
+            if in_array "$(ssid_to_profile "$ssid")" "${GENERATED[@]}"; then
                 ENTRIES[i]="+"  # Automatically generated
             else
                 ENTRIES[i]="*"  # Handmade
@@ -124,13 +121,13 @@ create_profile()
         fi
     fi
     cat << EOF > "$PROFILE_DIR/$PROFILE"
-CONNECTION='wireless'
-DESCRIPTION='Automatically generated profile by wifi-menu'
-INTERFACE='$INTERFACE'
-SECURITY='$security'
+Description='Automatically generated profile by wifi-menu'
+Interface=$INTERFACE
+Connection=wireless
+Security=$security
 ESSID=$(printf "%q" "$1")
 IP='dhcp'
-${key+KEY=$key}
+${key+Key=$key}
 EOF
     printf "%s" "$PROFILE"
     return 0
@@ -142,17 +139,14 @@ connect_to_ssid()
 {
     local msg
     PROFILE=$(ssid_to_profile "$1")
-    if [[ $? -eq 0 ]]; then
-        clear
-        check_profile "$PROFILE" && profile_down "$PROFILE"
-    else
+    if [[ $? -ne 0 ]]; then
         PROFILE=$(create_profile "$1")
         RETURN=$?
         (( RETURN == 0 )) || return $RETURN
         SPAWNED_PROFILE=1
-        clear
     fi
-    if ! profile_up "$PROFILE"; then
+    clear
+    if ! netctl restart "$PROFILE"; then
         if (( SPAWNED_PROFILE )); then
             msg="         CONNECTING FAILED
 
@@ -183,40 +177,35 @@ while [[ "$1" = -* ]]; do
     esac
 done
 if [[ $# -gt 1 ]]; then
-    report_err "Too many arguments"
+    report_error "Too many arguments"
     usage
     exit 255
 fi
 
-if [[ $(id -u) -ne 0 ]]; then
-    exit_stderr "This script needs to be run with root privileges"
-fi
+ensure_root "$(basename "$0")"
 if ! type dialog &> /dev/null; then
-    exit_stderr "Please install 'dialog' to use wifi-menu"
+    exit_error "Please install 'dialog' to use wifi-menu"
 fi
 
-INTERFACE=${1-$WIRELESS_INTERFACE}
+INTERFACE=${1-wlan0}
 if [[ -z "$INTERFACE" ]]; then
-    report_err "Missing interface specification"
+    report_error "Missing interface specification"
     usage
     exit 255
 fi
 
 cd /  # We do not want to spawn anything that can block unmounting
-is_interface "$INTERFACE" || exit_fail "No such interface: $INTERFACE"
-if ! interface_is_up "$INTERFACE"; then
-    [[ -f "$IFACE_DIR/$INTERFACE" ]] && . "$IFACE_DIR/$INTERFACE"
-    bring_interface up "$INTERFACE" || exit_fail "Interface unavailable"
-    SPAWNED_INTERFACE=1
+if [[ ! -d "/sys/class/net/$INTERFACE" ]]; then
+    exit_error "No such interface: $INTERFACE"
 fi
 
-report_try "Scanning for networks"
+echo -n "Scanning for networks... "
 CONNECTION=$(wpa_call "$INTERFACE" status 2> /dev/null | grep -m 1 "^ssid=")
 CONNECTION=${CONNECTION#ssid=}
 NETWORKS=$(wpa_supplicant_scan "$INTERFACE" 3,4,5)
 if [[ $? -eq 0 ]]; then
     trap 'rm -f "$NETWORKS"' EXIT
-    report_success
+    echo "done"
     init_profiles "$INTERFACE"
     init_entries "$NETWORKS"
     MSG="Select the network you wish to use
@@ -233,7 +222,7 @@ Flags description:
         RETURN=$?
     fi
 else
-    report_fail
+    echo "failed"
     RETURN=3
 fi
 
@@ -244,20 +233,19 @@ case $RETURN in
         clear
         ;;
     3)  # No networks found
-        report_err "No networks found"
+        report_error "No networks found"
         ;;
     4)  # Invalid passphrase length (WEP keys have tighter restrictions)
         clear
-        report_err "Passphrase must be 8..63 characters"
+        report_error "Passphrase must be 8..63 characters"
         ;;
     255)  # ESC or error
         clear
-        report_err "Aborted"
+        report_error "Aborted"
         ;;
     *)  # Should not happen
-        report_err "Unexpected return code from dialog: $RETURN"
+        report_error "Unexpected return code from dialog: $RETURN"
         RETURN=7
         ;;
 esac
-(( RETURN && SPAWNED_INTERFACE )) && bring_interface down "$INTERFACE"
 exit $RETURN
